version: "3.9"

services:
  web:
    build:
        context: .
        dockerfile: ./app/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./.env.db_auth.dev
      - ./.env.app.dev
      - ./.env.worker.dev
      - ./.env.rnb.dev
      - ./.env.sentry.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - ./app:/app
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgis/postgis:14-master
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db_auth.dev
    ports:
      - "5432:5432"
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks worker --loglevel=INFO
    volumes:
      - ./worker:/worker
      - ./source_data:/data/downloads
    env_file:
      - ./.env.db_auth.dev
      - ./.env.worker.dev
      - ./.env.rnb.dev
      - ./.env.sentry.dev
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3.9-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  blackd:
    restart: always
    image: docker.io/pyfound/black
    command: blackd --bind-host 0.0.0.0 --bind-port 45484
    ports:
      - "45484:45484"


volumes:
  postgres_data:
  rabbitmq_data: